# Generated by Django 4.2.2 on 2023-10-04 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashbord", "0002_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="staff",
        ),
    ]
