# Generated by Django 4.2.2 on 2023-09-27 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utilisateur", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="customer",
            new_name="staff",
        ),
    ]
